language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://tkoerner.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "sCHsssBNFnmwSaBNf4RiAn4deWNcl+gkaqrqchtFhUSNb+NA9KumUxiFe7HUyV+6RMF5D5Yo3iKPeCzuGs+S13+Pct79QpvZS0vX9oofsX3QdeHBXnRC3YRXxru32/t01Yg/gzJTnP/dlfGpqLp2u4WOObAKH+srR6kB55U6jIF/OSZnx81XGCFuVDn6FncC9vZSZQkwqyjOaXjihxfgQ6/s8dmgFD5plNhjS6zxko1+yCsfywlYk/yVDBdKVFM1uzyz0lChPbTj3k6AuL8mEErAiLg7Ebl94kEqGc7rDBlk+9LpekcrRsyk+E8tE0TWev8hK9nJz0NK8BWW9/JXiYf7S/CC3zF10iXJwDx1mQwN+U/B+Bha/0UQwsWJNHkEPZTHYNHSrm5JcP9WCqQDbVTiiOok3R8n/DcoEuFYNQnqKyZ+5rWwslyqcEwXjHvZXhjzlEZRzKzyJ7SOS1CjI1xQvcYAthtmgOHE/Q3xd2ntRozKR9miFTHdnC7JmRmYI8IEa4cNMTXKj83AqGMNVn0M3HxKhBFJqiK0YtXMiH3eFMCcKnbyCU/OCt9CZKTuNVVXEZRnbywJuZtLf2DglYe0/Z+tJBV8Lw8JATXZu6TtInCoFjc5wfLwpRWZRsEZGNAZZkwzgX11HwJb3UhX6Bkh+oDoKk4QpSlE67jmaoQ="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
